### PR TITLE
For Final Code Review --3:30pm

### PR DESCRIPTION
**Pull request by sailendrasingh1**
added a line "For Final Code Review" in both scripts

### CODE REVIEW

**Review by almabekwoldesenbet — CHANGES_REQUESTED** [review]
**Data collection section** 
- Remove Top 100 example line 84
-  I thing we agreed just flag -  D.RECORD_REGIS_DATE IS NOT NULL - This need to be confirmed with Avinash.  
**Parent section** 
- Why is scenario commented 
**loading to log and target** 
- why do you need PersionID is null checking. As long as flag = 1, it should be logged. 

UPDATE #Tmp_HoldData SET LOOKUP_TRX_FLG= '-2' WHERE LOOKUP_TRX_FLG = '-'
		UPDATE #Tmp_HoldData SET LOOKUP_TRX_INT_REJECT_CD= '-2' WHERE LOOKUP_TRX_INT_REJECT_CD = '-'
		UPDATE #Tmp_HoldData SET LOOKUP_TRX_SYS_REJECT_CD= '-2' WHERE LOOKUP_TRX_SYS_REJECT_CD = '-'
  ,ISNULL(TRX_SYS_REJECT_CD,'-2') AS LOOKUP_TRX_SYS_REJECT_CD
			  ,ISNULL(TRX_INT_REJECT_CD,'-2') AS LOOKUP_TRX_INT_REJECT_CD

**Validation** 
the below one should be warning b.c it's mismatch 

Data conversion  is required for the three Unknow of DIMs

CASE WHEN HD.UnderlyingCause IS NULL AND (HD.CAUSE_CATEGORY1 IS NOT NULL OR HD.CAUSE_CATEGORY2  IS NOT NULL OR HD.CAUSE_CATEGORY3  IS NOT NULL 
						OR HD.CAUSE_CATEGORY4 IS NOT NULL OR HD.CAUSE_CATEGORY5 IS NOT NULL OR HD.CAUSE_CATEGORY6 IS NOT NULL OR HD.CAUSE_CATEGORY7 IS NOT NULL 
						OR HD.CAUSE_CATEGORY8 IS NOT NULL OR HD.CAUSE_CATEGORY9  IS NOT NULL OR HD.CAUSE_CATEGORY10  IS NOT NULL OR HD.CAUSE_CATEGORY11 IS NOT NULL 
						OR HD.CAUSE_CATEGORY12  IS NOT NULL OR HD.CAUSE_CATEGORY13  IS NOT NULL OR HD.CAUSE_CATEGORY14  IS NOT NULL OR HD.CAUSE_CATEGORY15  IS NOT NULL 
						OR HD.CAUSE_CATEGORY16 IS NOT NULL OR HD.CAUSE_CATEGORY17  IS NOT NULL OR HD.CAUSE_CATEGORY18  IS NOT NULL OR HD.CAUSE_CATEGORY19  IS NOT NULL 
						OR HD.CAUSE_CATEGORY20  IS NOT NULL)
					THEN ''
LOAD 
remove insNULL ,ISNULL(CauseManual,'')
remove ISNULL(UnderlyingCause,'')

**Comment by sailendrasingh1** [comment]
Data collection section

Bezawit: Remove Top 100 example line 84
Mac: Can be moved from script

Bezawit: I thing we agreed just flag - D.RECORD_REGIS_DATE IS NOT NULL - This need to be confirmed with Avinash.
Mac: Removed it from filter condition

Bezawit: Parent section
Why is scenario commented
Mac: Scenario 1 cane be removed

Bezawit: loading to log and target
why do you need PersionID is null checking. As long as flag = 1, it should be logged.
Code changed to get records according to flag

Bezawit:UPDATE #Tmp_HoldData SET LOOKUP_TRX_FLG= '-2' WHERE LOOKUP_TRX_FLG = '-'
UPDATE #Tmp_HoldData SET LOOKUP_TRX_INT_REJECT_CD= '-2' WHERE LOOKUP_TRX_INT_REJECT_CD = '-'
UPDATE #Tmp_HoldData SET LOOKUP_TRX_SYS_REJECT_CD= '-2' WHERE LOOKUP_TRX_SYS_REJECT_CD = '-'
,ISNULL(TRX_SYS_REJECT_CD,'-2') AS LOOKUP_TRX_SYS_REJECT_CD
,ISNULL(TRX_INT_REJECT_CD,'-2') AS LOOKUP_TRX_INT_REJECT_CD
Mac: Had to do this logic due data retrieval problem. hence alter statement was used in the end of select statement and update was done to get '-2' for '-' values.

Validation
Bezawit: the below one should be warning b.c it's mismatch
Mac: Fixed

Bezawit: Data conversion is required for the three Unknow of DIMs
Mac: Clarified in meeting about the confusion and no conversion needed for dim in this case

CASE WHEN HD.UnderlyingCause IS NULL AND (HD.CAUSE_CATEGORY1 IS NOT NULL OR HD.CAUSE_CATEGORY2 IS NOT NULL OR HD.CAUSE_CATEGORY3 IS NOT NULL
OR HD.CAUSE_CATEGORY4 IS NOT NULL OR HD.CAUSE_CATEGORY5 IS NOT NULL OR HD.CAUSE_CATEGORY6 IS NOT NULL OR HD.CAUSE_CATEGORY7 IS NOT NULL
OR HD.CAUSE_CATEGORY8 IS NOT NULL OR HD.CAUSE_CATEGORY9 IS NOT NULL OR HD.CAUSE_CATEGORY10 IS NOT NULL OR HD.CAUSE_CATEGORY11 IS NOT NULL
OR HD.CAUSE_CATEGORY12 IS NOT NULL OR HD.CAUSE_CATEGORY13 IS NOT NULL OR HD.CAUSE_CATEGORY14 IS NOT NULL OR HD.CAUSE_CATEGORY15 IS NOT NULL
OR HD.CAUSE_CATEGORY16 IS NOT NULL OR HD.CAUSE_CATEGORY17 IS NOT NULL OR HD.CAUSE_CATEGORY18 IS NOT NULL OR HD.CAUSE_CATEGORY19 IS NOT NULL
OR HD.CAUSE_CATEGORY20 IS NOT NULL)
THEN ''
LOAD


Bezawit: remove insNULL ,ISNULL(CauseManual,'')
Mac: Removed
Bezawit: remove ISNULL(UnderlyingCause,'')
Mac: Removed

**Review by almabekwoldesenbet — APPROVED** [review]
looks good

**Comment by almabekwoldesenbet** [comment]
Work Item = 162   - 10/07/2022 -  Cause of Death ACME part has been done on 10/07/2022

**Pull request merged**
